spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification
      username: micho
      password: micho
      authentication-database: admin

server:
  port: 8040