spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: micho
    password: micho
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8060